- name: Copy node-exporter rule file
  copy: src=node_exporter.yml dest=/etc/prometheus/rules/node_exporter.yml

- name: Add node-exporter rules to prometheus config
  lineinfile:
    path: /etc/prometheus/prometheus.yml
    insertafter: 'rule_files:'
    line: '{{ item }}'
    backup: true
  with_items: ["   - rules/node_exporter.yml"]

- name: debug
  debug: msg={{ ansible_nodename }}

- name: Copy add_job for prometheus config dir 
  copy: src=add_job dest=/etc/prometheus/

- name: Add new job to prometheus config
  shell: echo | cat /etc/prometheus/add_job >> /etc/prometheus/prometheus.yml

- name: Replace "crutch_0" with real client hostname
  replace:
    dest: "/etc/prometheus/prometheus.yml"
    regexp: "crutch_0"
    replace: "{{ node_exporter_client_hostname }}"

- name: Replace "crutch_1" with real client ip
  replace:
    dest: "/etc/prometheus/prometheus.yml"
    regexp: "crutch_1"
    replace: "{{ node_exporter_client_ip }}"

- name: Start and Enable Prometheus Service
  service: name=prometheus state=restarted enabled=yes    



